- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.shell:
    ~/.zsh:
    ~/.zshrc:
    ~/.curlrc:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.vim:
    ~/.vimrc:
    ~/.tmux.conf:

- shell:
    - [./install_zsh.sh, Installing zsh]
    - command: echo -n "Password:"; chsh -s $(which zsh); echo ""
      stdin: true
      stdout: true
      description: Making zsh the default shell
    - command: ./install_tmux_locally.sh
      stdout: true
      description: Installing tmux
    - [git submodule update --init --recursive, Installing submodules]
