- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.shell:
    ~/.zsh:
    ~/.zshrc:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.vim:
    ~/.vimrc:
    ~/.tmux.conf:

- shell:
    - [sudo apt-get install git make build-essential, Install dependencies]
    - [. install_tmux_locally.sh, Install tmux]
    - [git submodule update --init --recursive, Installing submodules]
